# Generated by Django 5.0.3 on 2024-04-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=120)),
                ('address', models.TextField()),
                ('phone_number', models.IntegerField()),
                ('helper_assigned', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Helper_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helper_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=120)),
                ('gender', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('skills', models.TextField()),
                ('status', models.CharField(default='AVAILABLE', max_length=100)),
            ],
        ),
    ]
