# Generated by Django 5.0.3 on 2024-04-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_cust_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_info',
            name='helper_assigned',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
