# Generated by Django 5.0.3 on 2024-04-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_cust_app', '0002_alter_customer_info_helper_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_info',
            name='helper_assigned',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
